### ISSUE TITLE
English not your first language?

### ISSUE THREAD

**Issue by b-morgan** [hashashin/OctoPrint-OpiTemp#1]
Hi,
I'm guessing that English is not your native / first language but I believe that a large portion of your audience will be English speaking. For that reason, I'm offering a correction which jumped out at me.

The word "stealed" should be "stolen".

Its not that big a deal but I believe it helps present a more professional appearance.

**Comment by hashashin** [comment]
You're right Spanish it's my native language, thanks for the correction 😄.
