### ISSUE TITLE
Temp not being displayed but °C is showing.

### ISSUE THREAD

**Issue by leesirc2002** [hashashin/OctoPrint-OpiTemp#10]
There is no TEMP just °C (nothing else)

## Expected Behavior
Expecting a temperature readout

## Current Behavior
°C (nothing else)

## Possible Solution
No Idea

## Steps to Reproduce (for bugs)
1. Tried NavBar Temp Plugin (same result)

## Context
See the temperature of the RPI

## Your Environment

* Plugin v1.0.8 
* Octoprint v1.4
* Chrome v84.0.4147.89
* RPI v4B Rev 1.1

**Comment by diginfo** [comment]
I am using RPI4 and have the same problem, no temperature is displayed and this file / folder does not exist:

`/etc/armbianmonitor/datasources/soctemp`
