### ISSUE TITLE
Missing/empty "/etc/armbianmonitor/datasources/"

### ISSUE THREAD

**Issue by DyGyg** [hashashin/OctoPrint-OpiTemp#2]
Displays nothing...

**Comment by hashashin** [comment]
Hi @DyGyg, can you please confirm you're on armbian, the file "/etc/armbianmonitor/datasources/soctemp" exist and it's readable by the user that launched octoprint? Also the plugin should log exceptions, if any, in octoprint logs, so having the logs will be helpful.

Thanks, salud.

**Comment by DyGyg** [comment]
hi! Yes, i use Armbian 5.43 nightly.
I will check soctemp later, have no acces right now.
But I see alot of warnings in octoprint.log
`2018-04-25 00:18:20,226 - octoprint.plugins.opitemp - WARNING - OpiTemp REFRESH FAILED: 'NoneType' object has no attribute 'group'`

**Comment by DyGyg** [comment]
My /etc/armbianmonitor/datasources/ is empty ((

**Comment by hashashin** [comment]
@DyGyg it's the command: `sudo armbianmonitor -m` showing the temperature? if work you shoud see something like this:
```
Stop monitoring using [ctrl]-[c]
Time        CPU    load %cpu %sys %usr %nice %io %irq   CPU  C.St.

21:30:41: 1200MHz  0.18   3%   2%   1%   0%   0%   0% 53.4°C  0/8
```

**Comment by DyGyg** [comment]
```
Stop monitoring using [ctrl]-[c]
Time        CPU    load %cpu %sys %usr %nice %io %irq  C.St.

13:34:38:  816MHz  0.10   1%   0%   0%   0%   0%   0%  0/2
13:34:43:  816MHz  0.09   4%   1%   2%   0%   0%   0%  0/2
13:34:48:  816MHz  0.08   2%   1%   1%   0%   0%   0%  0/2
13:34:53:  816MHz  0.08   2%   0%   0%   0%   0%   0%  0/2
13:34:58:  816MHz  0.14   4%   1%   2%   0%   0%   0%  0/2
13:35:03:  816MHz  0.13   6%   2%   3%   0%   0%   0%  0/2

```

**Comment by DyGyg** [comment]
no temperature as i see (((

**Comment by DyGyg** [comment]
as i understand Armbian for Zero PLUS (and other boards with H5) is in "experimental" status 
https://www.armbian.com/orange-pi-zero-plus/
so will wait - maybe someday this will be fixed...

**Comment by DyGyg** [comment]
hm.... the strange thing  that at another Zero PLUS i see file "/etc/armbianmonitor/datasources/soctemp"
and armbianmonitor outputs the temperature:
```
Stop monitoring using [ctrl]-[c]
Time        CPU    load %cpu %sys %usr %nice %io %irq   CPU  C.St.

15:40:30:  408MHz  0.24   9%   2%   6%   0%   1%   0% 70.1°C  2/2
15:40:35:  408MHz  0.22   0%   0%   0%   0%   0%   0% 69.8°C  2/2
```

**Comment by DyGyg** [comment]
heheeey!
on second Zero Plus the /etc/armbianmonitor/datasources/soctemp is a link to /sys/devices/virtual/thermal/thermal_zone0/temp
i've made the same link at first device (on which Octoprint is running) and see temperature in output of "armbianmonitor -m" :) 
will try to reinstall your plugin after my current printing will finished

**Comment by hashashin** [comment]
Armbian could be odd sometimes, right now I've 2 exacts installs if it on 2 Opi zero, one has armbianmonitor  command missing for some reason after an apt upgrade. I'm asking in IRC chat right now, cause I can't even find the deb package which armbianmonitor belongs to...

I'm pretty sure the plugin will work now on your install.

**Comment by DyGyg** [comment]
yes, the plugin works now :)
the problem is the link absent after reboot :\
when i recreate it - everithing is fine...

**Comment by hashashin** [comment]
I'm glad it's working now, closing this then.

Thanks, salud.

**Comment by DyGyg** [comment]
i reboot second Zero Plus and have no symlink to %))))
i dont understand when it was created first time i've seen it

**Comment by DyGyg** [comment]
i found it in /etc/init.d/armhwinfo ....
still don't understad why it works sometimes, and sometimes - not
will try to figure it out.
anyway - it's not problem of yor plugin )  thanks for it )

**Comment by hashashin** [comment]
Perhaps making an "advanced" config option to customize the file to read from directly? 
For example: `/sys/devices/virtual/thermal/thermal_zone0/temp` 
You have to know what are doing, because it can be also: `/sys/devices/virtual/thermal/thermal_zone1/temp` or whatever depending on the SOC.
It should be readable for the user anyway, but that could change in the future.

I'm gonna reopen this, change a bit the description and leave it in case more people have the same issue and I'll think about the above then.

Thanks for the feedback @DyGyg.

**Comment by DyGyg** [comment]
good idea about advanced config option!

**Comment by DyGyg** [comment]
i've found fix for me - i've put "sleep 5" in /etc/init.d/armhwinfo before temperatur monitor initiaization.
Try to reboot both Zero Plus boards about 5-7 times  - soctemp symlink is there.
but anyway advanced option what file to read will be great

**Comment by DyGyg** [comment]
hi! i've checked advanced option in 1.0.6 
workin fine! thanks
i think this issue may be closed

**Comment by hashashin** [comment]
hi @DyGyg, thanks again for the feedback. 
I'm closing this then, with the new error msg in the OctoPrint log people should be able to figure out what's wrong (missing-empty "/etc/armbianmonitor/datasources/soctemp" file). And hopefully fix it through the new option.

Salud.
