### ISSUE TITLE
Doesn't work with Orange Pi Zero

### ISSUE THREAD

**Issue by knyazyok** [hashashin/OctoPrint-OpiTemp#3]
It shows 0.0 or 0.1 in navbar
From OS I can read temperature:
root@orangepizero:~# su - octoprint

octoprint@orangepizero:~$ cat /etc/armbianmonitor/datasources/soctemp
49

**Comment by hashashin** [comment]
Weird, which armbian version/kernel? 
Can you please paste the output of: "`cat /etc/armbian-release`"  and "`uname -r`" ?

On two Opi Zero I've they show the temp like this:
```
cat /etc/armbianmonitor/datasources/soctemp
46101
```

**Comment by knyazyok** [comment]
```
root@orangepizero:~# cat /etc/armbian-release
# PLEASE DO NOT EDIT THIS FILE
BOARD=orangepizero
BOARD_NAME="Orange Pi Zero"
BOARDFAMILY=sun8i
VERSION=5.38
LINUXFAMILY=sun8i
BRANCH=default
ARCH=arm
IMAGE_TYPE=stable
BOARD_TYPE=conf
INITRD_ARCH=arm
KERNEL_IMAGE_TYPE=zImage
root@orangepizero:~# uname -r
3.4.113-sun8i
```

**Comment by hashashin** [comment]
Thanks. 
I'm almost sure the problem it's the kernel version, my Opis have 4.x which is BRANCH=next. 
You can switch with the armbian-config tool. If that's not an option, you'll need to wait until I figure out a way to detect armbian release/kernel, which I already have some ideas.

**Comment by hashashin** [comment]
@knyazyok can you please test this ~~quick~~ ugly fix: https://github.com/hashashin/OctoPrint-OpiTemp/archive/fix%233.zip
If works I'll do a release, thanks.

**Comment by knyazyok** [comment]
Hi @hashashin !

How should I install the fix? Through Plugin Manager in Octoprint?

**Comment by hashashin** [comment]
In the Octoprint interface: Settings -> Plugin Manager -> Get More -> ... from URL
Then paste there the link and click install.

**Comment by knyazyok** [comment]
Ok, just finish my current printing (2-3 hrs) and try

**Comment by knyazyok** [comment]
@hashashin tried your fix - working good now

**Comment by hashashin** [comment]
Version bumped to 1.0.1 with the fix included, thanks for testing it.
