### ISSUE TITLE
No temperature displayed - Raspberry Pi 3B

### ISSUE THREAD

**Issue by tumbleweedlabs** [hashashin/OctoPrint-OpiTemp#5]
Hello, I installed this plugin but it just shows a white degree celsius, no other data. 
![screen shot 2018-04-29 at 12 44 14 pm](https://user-images.githubusercontent.com/4380794/39410286-12680b76-4bab-11e8-9b6f-6eafa44b4560.png)

**Comment by hashashin** [comment]
Hi @tumbleweedlabs.
Are you using raspbian? This plugin is intended to be used on the distro armbian (orange pi usually).
For raspbian you can try [OctoPrint-NavbarTemp](https://plugins.octoprint.org/plugins/navbartemp/) which has an option to show rpi temperature.

**Comment by tumbleweedlabs** [comment]
Aha! Thank you.

**Comment by hashashin** [comment]
You're welcome.

Salud.
