### ISSUE TITLE
temperature cannot show current temp

### ISSUE THREAD

**Issue by tjengbudi** [hashashin/OctoPrint-OpiTemp#7]
!--- Provide a general summary of the issue in the Title above -->
it is always 0 celcius. i checked with terminal and /etc/armbianmonitor/datasources/soctemp and replied working current temp. so it might failed get the code only

## Expected Behavior

showing current cpu temp

## Current Behavior

the temperature always show 0

## Steps to Reproduce (for bugs)

1. just installed
2. reboot octoprint

## Your Environment

* Version of both Octoprint and this plugin:
* Browser Name and version:
* Operating System and version running Octoprint instance:
chrome Version 78.0.3904.70 (Official Build) (64-bit)
octoprint 1.3.12 latest

**Comment by xoan** [comment]
Probably related to kernel version and 1a1af0e407c7a9db3f67e744e259b1c2311bd27f

Using 5.3.x doesn't match any condition and returns temp = 0.
